Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/nbclient/client.py", line 1269, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/nbclient/client.py", line 707, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/nbclient/client.py", line 1025, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/nbclient/client.py", line 919, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
data = requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/fastformula/" + formula +"/property/MolecularFormula,IsomericSMILES/CSV").text.strip()

cid_props = {}
reader = csv.reader(io.StringIO(data))
print(next(reader))  # Print the first line (column header)

for row in reader:
    key = row[0]
    cid_props[key] = row[1:]

count = 0
for item in cid_props:
    
    count += 1
    print(item, "\t", cid_props[item][0], "\t", cid_props[item][1])
    if count == 10 :  # For simplicity, print only the first 10 items.
        break
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
Cell [0;32mIn[18], line 15[0m
[1;32m     12[0m [38;5;28;01mfor[39;00m item [38;5;129;01min[39;00m cid_props:
[1;32m     14[0m     count [38;5;241m+[39m[38;5;241m=[39m [38;5;241m1[39m
[0;32m---> 15[0m     [38;5;28mprint[39m(item, [38;5;124m"[39m[38;5;130;01m\t[39;00m[38;5;124m"[39m, [43mcid_props[49m[43m[[49m[43mitem[49m[43m][49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m, [38;5;124m"[39m[38;5;130;01m\t[39;00m[38;5;124m"[39m, cid_props[item][[38;5;241m1[39m])
[1;32m     16[0m     [38;5;28;01mif[39;00m count [38;5;241m==[39m [38;5;241m10[39m :  [38;5;66;03m# For simplicity, print only the first 10 items.[39;00m
[1;32m     17[0m         [38;5;28;01mbreak[39;00m

[0;31mIndexError[0m: list index out of range
IndexError: list index out of range

